### ISSUE TITLE
Add netlifycms instance

### ISSUE THREAD

**Issue by davkal** [grafana/grafana.org#151]
Add a netlifycms instance to make sure we can edit blog posts and pages with it.

**Comment by jschill** [comment]
WIP:

Available here: https://github.com/grafana/grafana.org/tree/netlifycms

Checkout the `netlifycms`-branch, run the server (`grunt && grunt watch` and in another tab: `grunt connect`) and then go to http://localhost:3002/admin

You will authenticate against Github since we dont have our own oAuth ([yet](https://github.com/grafana/grafana.org/issues/152)).

Changes (adding images, editing/adding blog posts...)  done in the cms will be pushed to the `cms`-branch (https://github.com/grafana/grafana.org/tree/cms). Nothing happens from there, so we need a strategy how we want deployments to staging/prod.

**Comment by davkal** [comment]
Requirements:
Ideally, authors do some editing, and then when they are happy, they can create a PR straight from the cms. Also, concurrent edits should work, e.g., author 1 edits one post, while author 2 edits a different page. When both decide to commit their changes and open a PR, the PRs should not contain each others' work.

**Comment by jschill** [comment]
WIP:

Same procedure as above, but use the `151-netlifycms` branch.
